name: Deploy static content to Pages
on:
  push:
    branches: ["master"]
    workflow_dispatch:
jobs:
  publish: 
    runs-on: ubuntu-latest
    steps:
      - name: move 
        run: |
          mkdir docs
          cp -r PrefFlow2022_files docs
          cp PrefFlow2022.html docs